### ISSUE TITLE
Analyse sur un article du SPS325

### ISSUE THREAD

**Issue by JimRou** [gaelm/afis-moulinette#1]
Analyse par Jimmy Roussel 
Test du script sur SPS_325-P_10-15.epub
2019-01-10

BUGS rencontrés
- Les encadrés ne sont pas pris en charge, mais j'ai l'impression que c'est lié à l'export InDesign->EPUB qui les fait disparaître...
- les références dans les cadres ont disparues
- de nombreuses parties du texte principal sont mélangées ou ont disparu ? (je me demande si ça n'est pas lié aux césures et/ou à la conversion InDesign>Epub)

TODO
- changement de paragraphe à implémenter (il faut ajouter un saut de ligne)
- il faudrait ignorer les entêtes et pieds de page du document source
- les titres sont mal pris en charge : {{{ {{titre niveau 1}} }}} au lieu de {{{titre niveau 1 }}}

**Comment by gaelm** [comment]
Pour les parties de texte manquantes, cela venait de mon utilisation de ElementTree dans laquelle je ne prenais pas en compte les tails:
https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.tail

J'ai aussi corrigé les sauts de lignes manquants et essayé d'enlever les entêtes et pieds de page.
